image: python:3.7.3

pipelines:
  default:
    - step:
        name: Send to S3 for Security Review
        caches:
          - pip
        script: 
          - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          - export AWS_S3_BUCKET=$AWS_S3_BUCKET
          - export REPO_NAME=$REPO_NAME
          - export AWS_REGION=$AWS_REGION
          - pip install awscli
          - tar -zcvf /tmp/$REPO_NAME.tar.gz ./
          - aws s3 cp /tmp/$REPO_NAME.tar.gz s3://$AWS_S3_BUCKET/
