image: ubuntu-latest

pipelines:
  default:
    - step:
        name: Send to S3 for Security Review
        caches:
          - pip
        script: 
          - export AWS_ACCESS_KEY=$AWS_ACCESS_KEY
          - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          - export AWS_S3_BUCKET=$AWS_S3_BUCKET
          - export REPO_NAME=$REPO_NAME
          - export AWS_REGION=$AWS_REGION
          - mkdir ./temp
          - pip install awscli
          - tar -zcvf ./temp/$UPLOAD_NAME.tar.gz ./
          - aws s3 cp ./temp/$UPLOAD_NAME.tar.gz s3://$AWS_S3_BUCKET/
