name: Send_For_Security_Review


on:
  push:
    branches: [ Security ]
  pull_request:
    branches: [ Security ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Create temp dir
      run: mkdir ./temp
      
    - name: Install AWS CLI
      run: pip install awscli
      
    - name: Create tar and upload to S3
      run: |
        tar -zcvf ./temp/$UPLOAD_NAME.tar.gz ./
        aws s3 cp ./temp/$UPLOAD_NAME.tar.gz s3://$AWS_S3_BUCKET/
      env: 
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        UPLOAD_NAME: ${{ secrets.UPLOAD_NAME  }}
        # Optionally set the name of the project where it is visible instead of encrypting it in secrets
        #UPLOAD_NAME: 'Awesome_Project_1'
